### PR TITLE
Init fixes

### PR DESCRIPTION
**Pull request by linosanfilippo-kunbus**
Fixes for the revpi_compact_init() Funktion.

### CODE REVIEW

**Comment by l1k** [comment]
I've cherry-picked & pushed 36349b3 as 748d9b6.

Re: 600309d, I've gone with a slightly different solution, see c858ad3. Let me know if you have any objections.

Re: c614ac0, I'll get back to you in a bit.

**Comment by l1k** [comment]
Re: c614ac0, the bug is real but the solution doesn't work properly I'm afraid because `iio_channel_release()` is called with an `ERR_PTR()` which it can't handle. I'm proposing b50f4be instead. Let me know if you have any objections.

**Comment by linosanfilippo-kunbus** [comment]
> 
> Re: [600309d](https://github.com/RevolutionPi/piControl/commit/600309d4d3fb10a41f5113f69662e0c325aba234), I've gone with a slightly different solution, see [c858ad3](https://github.com/RevolutionPi/piControl/commit/c858ad328206579349b5c4b9d133fbfeba86ef62). Let me know if you have any objections.

The issue I was trying to fix was a premature decrease of the reference counters for the devices we are using as "ain_dev" and "aout_dev". Calling iio_channel_get_all()/iio_channel_get() both do not increase the reference counter  AFAICS. So must not put it until we are done with both devices (i.e. until we cleanup the module).

**Comment by linosanfilippo-kunbus** [comment]
> Re: [c614ac0](https://github.com/RevolutionPi/piControl/commit/c614ac0db6727f30b36e2f94402fb70d34f9f412), the bug is real but the solution doesn't work properly I'm afraid because `iio_channel_release()` is called with an `ERR_PTR()` which it can't handle. I'm proposing [b50f4be](https://github.com/RevolutionPi/piControl/commit/b50f4bea2067e68ff8ce63dfe18e55e786997140) instead. Let me know if you have any objections.

I agree, your solution also makes the code much cleaner by removing this logical ORed error check

**Comment by l1k** [comment]
> > Re: [600309d](https://github.com/RevolutionPi/piControl/commit/600309d4d3fb10a41f5113f69662e0c325aba234), I've gone with a slightly different solution, see [c858ad3](https://github.com/RevolutionPi/piControl/commit/c858ad328206579349b5c4b9d133fbfeba86ef62). Let me know if you have any objections.
> 
> The issue I was trying to fix was a premature decrease of the reference counters for the devices we are using as "ain_dev" and "aout_dev". Calling iio_channel_get_all()/iio_channel_get() both do not increase the reference counter AFAICS. So we must not put it until we are done with both devices (i.e. until we cleanup the module).

It seems to me they do increase the refcount:

```
iio_channel_get_all()
    list_for_each_entry()
        iio_device_get()
            get_device()
```

```
iio_channel_get()
    iio_channel_get_sys()
        list_for_each_entry()
            iio_device_get()
                get_device()
```

Am I missing something? Thanks.

**Comment by linosanfilippo-kunbus** [comment]
> > > Re: [600309d](https://github.com/RevolutionPi/piControl/commit/600309d4d3fb10a41f5113f69662e0c325aba234), I've gone with a slightly different solution, see [c858ad3](https://github.com/RevolutionPi/piControl/commit/c858ad328206579349b5c4b9d133fbfeba86ef62). Let me know if you have any objections.
> > 
> > 
> > The issue I was trying to fix was a premature decrease of the reference counters for the devices we are using as "ain_dev" and "aout_dev". Calling iio_channel_get_all()/iio_channel_get() both do not increase the reference counter AFAICS. So we must not put it until we are done with both devices (i.e. until we cleanup the module).
> 
> It seems to me they do increase the refcount:
> 
> ```
> iio_channel_get_all()
>     list_for_each_entry()
>         iio_device_get()
>             get_device()
> ```
> 
> ```
> iio_channel_get()
>     iio_channel_get_sys()
>         list_for_each_entry()
>             iio_device_get()
>                 get_device()
> ```
> 
> Am I missing something? Thanks.

I haven't looked into this function, maybe it also takes one or more references to the device. However I suggest to not rely on the internal handling of some other functions but to stick with the usual pattern in our own code: take a ref, do something with it and once we are done, release it.
But I do not have a strong opinion about this and AFAIK the code is to be refactored anyway in future, so go ahead with the solution you prefer.

**Pull request closed without merging**
