### PR TITLE
Rebase devel/revpi-5.10 on master [REVPI-3354]

### PR DESCRIPTION
**Pull request by tboehler1**
This is the devel/revpi-5.10 branch but rebased on master. All conflicts have been resolved and the source is now identical with PR #96.
This has not been tested as building failed with a missing header, but I can (and want to) test this, given some guidance how.

### CODE REVIEW

**Comment by nbuchwitz** [comment]
> [...] This has not been tested as building failed with a missing header, but I can (and want to) test this, given some guidance how.

You need to build the module against a kernel branch, which has picontrol serdev support (eg. 6.1 branch, https://github.com/RevolutionPi/linux/tree/devel/revpi-6.1).

**Comment by nbuchwitz** [comment]
Before we can merge this PR (which LGTM), we need to create a revpi-5.10 branch from the current master. Also we should mention the difference between both branches in the README

**Comment by nbuchwitz** [comment]
A little reminder for myself: Update the CI after we've switched the branches. Otherwise the snapshot packages won't build.

**Review by l1k — CHANGES_REQUESTED** [review]
You've got two commits on this branch with identical commit message but different code changes:

- a6cf9c2688c6 ("Connect 4/Core SE/Connect SE: Don't set SPI prio")
- 8ddf47b35265 ("Connect 4/Core SE/Connect SE: Don't set SPI prio")

You need to get rid of 8ddf47b35265 by redoing the rebase of 529c9a57b4c3 ("piControl: use serdev based revpi-comm device for RS485 communication") properly. 

Note that the original version of that commit, b6939a1d6b5e, deletes the `kthread_run(&UartThreadProc, ...)` call, yet your version 529c9a57b4c3 still contains it. Your version of the commit won't even compile because you're referencing `piCore_g.pUartThread` in `pibridge_probe()`, yet you're deleting the `pUartThread` member from `struct _SRevPiCore` in that commit.

Please make sure that *every* commit in your pull request compiles without errors or warnings. First compile-test the tip of your branch, then use `git checkout HEAD^` to jump to the preceding commit and recompile. Rinse, repeat until you've reached current master.

Why is it important that every commit compiles cleanly? Because down the road someone may have to use `git bisect` to find the commit which broke something. You're making their lives harder if you intermittently break the build.

Also, whenever a commit doesn't apply cleanly and requires resolution of non-trivial conflicts, please make sure that you add something like this at the bottom of the commit message:

```
[thomas: rebase from serdev branch onto master]
Signed-off-by: Thomas Böhler <t.boehler@kunbus.com>
```

Thereby you assume responsibility for any breakage you may inadvertently introduce through an incorrect conflict resolution.

Thanks!

**Comment by tboehler1** [comment]
Thank you @l1k for the high-quality review!

I've rebased the `devel/revpi-5.10` branch onto `master` again and managed to finally compile piControl after a few hiccoughs. All commits on top of master now compile and every commit that couldn't be applied cleanly has an appropriate message added at the bottom of the commit, as well as my sign off.

There is one thing I find curious: I cannot seem to build the latest commit on `master` on my RevPi:

<details>
<summary>Build log for <code>master</code></summary>

```
pi@RevPi97143:~/piControl $ git log -1
commit ce239ff0c0d8d6c6556dc47c5b2dbfbb44969cd9 (HEAD -> master, upstream/master)
Author: Nicolai Buchwitz <n.buchwitz@kunbus.com>
Date:   Thu Jul 6 11:43:26 2023 +0200

    Add README with basic build instructions

    Add a README file which describes the build process of the piControl module.
    This will ease the onboarding process for new developers and customers, who
    want to make changes or contribute to the upstream development.

    Signed-off-by: Nicolai Buchwitz <n.buchwitz@kunbus.com>
pi@RevPi97143:~/piControl $ git status
On branch master
nothing to commit, working tree clean
pi@RevPi97143:~/piControl $ KDIR=/usr/src/linux-headers-$(uname -r)/ make
echo "#define COMPILETIME \""`date`"\"" > compiletime.h
make -C /usr/src/linux-headers-6.1.38-rt12-v8/ M=/home/pi/piControl  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.38-rt12-v8'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /home/pi/piControl/piControlMain.o
  CC [M]  /home/pi/piControl/piIOComm.o
/home/pi/piControl/piIOComm.c: In function ‘piIoComm_open_serial’:
/home/pi/piControl/piIOComm.c:179:3: error: unknown type name ‘mm_segment_t’
  179 |   mm_segment_t oldfs;
      |   ^~~~~~~~~~~~
/home/pi/piControl/piIOComm.c:181:11: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
  181 |   oldfs = get_fs();
      |           ^~~~~~
      |           sget_fc
/home/pi/piControl/piIOComm.c:182:3: error: implicit declaration of function ‘set_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
  182 |   set_fs(KERNEL_DS);
      |   ^~~~~~
      |   sget_fc
/home/pi/piControl/piIOComm.c:182:10: error: ‘KERNEL_DS’ undeclared (first use in this function); did you mean ‘KERNFS_NS’?
  182 |   set_fs(KERNEL_DS);
      |          ^~~~~~~~~
      |          KERNFS_NS
/home/pi/piControl/piIOComm.c:182:10: note: each undeclared identifier is reported only once for each function it appears in
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:257: /home/pi/piControl/piIOComm.o] Error 1
make[1]: *** [Makefile:2035: /home/pi/piControl] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.38-rt12-v8'
make: *** [Makefile:39: all] Error 2
pi@RevPi97143:~/piControl $
```
</details>

Other than that, everything seems to be in order for me now.

**Comment by l1k** [comment]
```
/home/pi/piControl/piIOComm.c:181:11: error: implicit declaration of function ‘get_fs’; did you mean ‘sget_fc’? [-Werror=implicit-function-declaration]
```
That's expected and is the reason for the serdev migration in the first place. Commit torvalds/linux@8ac6f5d7f84b removed `set_fs()` on ARM 32-bit. That commit went into v5.15, preventing piControl from compiling with any LTS kernel beyond v5.10. Back in the day a decision was made to fix the issue by migrating to serdev, see REVPI-2360 for details.

**Comment by l1k** [comment]
Signed-off-by tags are always top to bottom. So the original author(s) of the patch are at the top and any intermediaries who pass the patch around, edit it or apply it add their Signed-off-by below. Any comments in square brackets go immediately before the Signed-off-by of the person adding those comments. No additional blank lines. See torvalds/linux@995585ecdf42 or torvalds/linux@2b5ae9604949 for an example.

**Comment by tboehler1** [comment]
Seems like I read the documentation[1] wrong, thanks for the correction! The commit messages should be okay now, hopefully.

[1]: https://docs.kernel.org/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Review by l1k — CHANGES_REQUESTED** [review]
There's an issue in fa95daf. This hunk is missing (it is present in the corresponding commit ea7d6db):
```
diff --git a/piIOComm.h b/piIOComm.h
index c60907b..905e8f5 100644
--- a/piIOComm.h
+++ b/piIOComm.h
@@ -40,8 +40,6 @@
 #define REV_PI_IO_TIMEOUT           10         // msec
 #define REV_PI_RECV_BUFFER_SIZE     100
 
-#define REV_PI_RECV_IO_HEADER_LEN	65530
-
 #define REV_PI_TTY_DEVICE	"/dev/ttyAMA0"
 
 enum IOSTATE {
```

**Comment by tboehler1** [comment]
@l1k Should be fixed now:

https://github.com/RevolutionPi/piControl/pull/97/commits/e554f4bc06cd42b24e961a189094526a1fcd8a29#diff-d36ee2ecc42df29f43f9d53ceccff199af37d804dc54218ef1b058e470cd8a1fL43

**Review by l1k — DISMISSED** [review]

**Comment by l1k** [comment]
> Before we can merge this PR (which LGTM), we need to create a revpi-5.10 branch from the current master. Also we should mention the difference between both branches in the README

So who's gonna do that? I'm not even sure I have permission to create that branch. In theory the serdev changes should work both with 5.10 and 6.1. Or am I missing something?

**Comment by l1k** [comment]
Okay we'd need to merge the serdev changes for the kernel into the RevolutionPi/linux repo's revpi-5.10 branch for it to compile against piControl. I guess we don't want to do that at least at this point?

**Comment by l1k** [comment]
@iluminat23 As discussed I've created a revpi-5.10 branch. Turns out I do have permission for that after all.

**Comment by tboehler1** [comment]
I have pushed a small change for the README that shortly explains the differences between the master and `revpi-5.10` branches.
@nbuchwitz is this sufficient?

**Review by l1k — CHANGES_REQUESTED** [review]
Technically, the requirement isn't serdev support (that's been in the kernel since <a href="https://elinux.org/images/0/0e/Serdev-elce-2017-2.pdf">4.12</a>). It's presence of the <a href="https://github.com/RevolutionPi/linux/blob/revpi-6.1/drivers/tty/serdev/pibridge.c">pibridge serdev driver</a> that's required.

The master branch can't be built against an *arbitrary* 6.1 kernel. It has to be revpi-6.1 because only that branch contains the pibridge serdev driver.

I'd link directly to the <a href="https://github.com/RevolutionPi/linux/commits/devel/revpi-6.1">revpi-6.1</a> and <a href="https://github.com/RevolutionPi/linux/commits/revpi-5.10">revpi-5.10</a> kernel branches.

**Review by nbuchwitz — APPROVED** [review]
- [x] Rebase serdev branch with `master`
- [x] Update README to reflect changes
- [x] Create `revpi-5.10` branch from current `master`

-> LGTM (keep in mind that https://github.com/RevolutionPi/linux/pull/159 needs to be merged after this is done)

**Review by l1k — APPROVED** [review]

**Pull request merged**
