### PR TITLE
Add support Connect 4 (serdev)

### PR DESCRIPTION
**Pull request by nbuchwitz**
This is my first series for RevPi Connect 4 support and targets the serdev branch. Nevertheless most of the commits can be cherry-picked to our "classic" piControl (+ the ttyAMA1 vs ttyAMA0 fix we spoke about).

Please note that the first 4 commits are picked from master and should not need additional reviews. As there are more commits missing from master a rebase of the serdev branch might be a good idea.

### CODE REVIEW

**Comment by l1k** [comment]
Needs to be updated to match #94 once the dust has settled over there.

**Review by l1k — CHANGES_REQUESTED** [review]
_

**Comment by nbuchwitz** [comment]
@l1k I've cherry-picked the relevant commits for Connect 4 from master (minus the ttyAMA1 stuff) and force-pushed this PR.

**Review by l1k — APPROVED** [review]

**Comment by nbuchwitz** [comment]
@l1k there was one commit missing "Connect 4: Add FW type description id", did a force push again. Rest is identical...

**Review by l1k — APPROVED** [review]

**Pull request merged**
